# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movies' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movies
  pod 'RxSwift', '4.0'
  pod 'RxCocoa', '4.0'
  pod 'IQKeyboardManagerSwift', '5.0.0'
  pod 'Kingfisher', '4.6'

end
